# Generated by Django 4.2.8 on 2023-12-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, unique=True, verbose_name='Identificação:')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nacimento:')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça:')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo:')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor:')),
                ('marcacoes', models.TextField(blank=True, null=True, verbose_name='Marcações:')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animal_photos/', verbose_name='Foto:')),
            ],
        ),
    ]
