# Generated by Django 5.0 on 2023-12-22 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaudeMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField()),
                ('tipo_registro', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_animais.animal')),
            ],
        ),
    ]
