# Generated by Django 5.0 on 2023-12-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saudemedicamento',
            name='dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saudemedicamento',
            name='local_atendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saudemedicamento',
            name='medicamento_utilizado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saudemedicamento',
            name='resultado_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saudemedicamento',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
