# Generated by Django 5.0 on 2023-12-26 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (em R$)')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_animais.animal')),
            ],
        ),
    ]
