# Generated by Django 5.0 on 2023-12-23 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesagem', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_animais.animal')),
            ],
        ),
    ]
