# Generated by Django 5.0 on 2023-12-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genealogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_animal', models.ImageField(blank=True, null=True, upload_to='genealogia_fotos/')),
                ('foto_pai', models.ImageField(blank=True, null=True, upload_to='genealogia_fotos/')),
                ('foto_mae', models.ImageField(blank=True, null=True, upload_to='genealogia_fotos/')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genealogia', to='cadastro_animais.animal')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendentes_mae', to='cadastro_animais.animal')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendentes_pai', to='cadastro_animais.animal')),
            ],
        ),
    ]
